{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dam-plugin.fullname" . }}
  labels:
    {{- include "dam-plugin.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.plugin.apiKey }}
  pluginApiKey: {{ .Values.plugin.apiKey | b64enc | quote }}
  {{- else }}
  pluginApiKey: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.externalApiKey }}
  externalApiKey: {{ .Values.secrets.externalApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
