#!/bin/bash
# =============================================================================
# Environment Configuration Loader
# =============================================================================
# Safely load environment-specific configuration
# Usage: source scripts/load-env.sh [local|dev|uat|prod]
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Default to local if not specified
ENV=${1:-local}

ENV_FILE="${PROJECT_ROOT}/.env.${ENV}"

# Function to print colored messages
log_info() {
  echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
  echo -e "${RED}✗${NC} $1"
}

# Check if environment file exists
if [ ! -f "$ENV_FILE" ]; then
  log_error "Environment file not found: $ENV_FILE"
  echo ""
  echo "Available environments:"
  echo "  ${GREEN}local${NC} - Local development"
  echo "  ${GREEN}dev${NC}   - Development cluster"
  echo "  ${GREEN}uat${NC}   - UAT/Staging cluster"
  echo "  ${GREEN}prod${NC}  - Production cluster"
  echo ""
  echo "Usage: source scripts/load-env.sh [local|dev|uat|prod]"
  echo ""
  echo "First time setup:"
  echo "  ${YELLOW}cp .env.${ENV}.example .env.${ENV}${NC}"
  echo "  ${YELLOW}nano .env.${ENV}${NC}  # Edit with your values"
  exit 1
fi

# Load environment variables
echo "Loading environment: ${GREEN}$ENV${NC}"
set -a  # Automatically export all variables
source "$ENV_FILE"
set +a

# Validate required variables
REQUIRED_VARS=(
  "PROJECT_NAME"
  "NAMESPACE"
  "DOCKER_REGISTRY"
  "IMAGE_NAME"
)

MISSING_VARS=()
for var in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!var}" ]; then
    MISSING_VARS+=("$var")
  fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
  log_error "Missing required environment variables:"
  printf '  - %s\n' "${MISSING_VARS[@]}"
  echo ""
  echo "Edit your environment file: ${YELLOW}$ENV_FILE${NC}"
  exit 1
fi

# Validate production environment
if [[ "$ENV" == "prod" ]] || [[ "$ENV" == "production" ]]; then
  log_warn "Production environment detected - Security checks:"
  
  # Check for default passwords
  if [[ "$DX_PASSWORD" == "<"* ]]; then
    log_error "Production passwords must not be defaults or placeholders!"
    log_error "Use Kubernetes secrets for production credentials"
    exit 1
  fi
  
  # Check CORS configuration
  if [[ "$CORS_ORIGIN" == "*" ]]; then
    log_error "CORS_ORIGIN cannot be wildcard (*) in production!"
    exit 1
  fi
  
  # Check DEBUG mode
  if [[ "$ENABLE_DEBUG_MODE" == "true" ]]; then
    log_error "ENABLE_DEBUG_MODE must be false in production!"
    exit 1
  fi
  
  log_info "Production security checks passed"
fi

# Display loaded configuration
echo ""
log_info "Environment loaded successfully"
echo "   Project: ${GREEN}$PROJECT_NAME${NC}"
echo "   Namespace: ${GREEN}$NAMESPACE${NC}"
echo "   Environment: ${GREEN}$ENV${NC}"
echo "   Node Environment: ${GREEN}${NODE_ENV}${NC}"
echo "   Docker Registry: ${GREEN}$DOCKER_REGISTRY${NC}"
echo "   Image: ${GREEN}$IMAGE_NAME:$IMAGE_TAG${NC}"

# Optional: Export to a file for other scripts to source
ENV_EXPORT_FILE="${PROJECT_ROOT}/.env.loaded"
cat > "$ENV_EXPORT_FILE" << EOF
# Auto-generated by load-env.sh - DO NOT EDIT
# Loaded environment: $ENV at $(date)
export LOADED_ENV="$ENV"
EOF

# Append all variables
set | grep -E "^(PROJECT_|NAMESPACE|DOCKER_|IMAGE_|DX_|WCM_|SERVICE_|API_|PLUGIN_|DAM_|LOG_|HELM_)" >> "$ENV_EXPORT_FILE" || true

log_info "Environment variables exported to: ${ENV_EXPORT_FILE}"
echo ""
echo "To use in your current shell:"
echo "  ${YELLOW}source $ENV_FILE${NC}"
echo "  ${YELLOW}# or${NC}"
echo "  ${YELLOW}source $ENV_EXPORT_FILE${NC}"
